language: python
python:
  - 2.5
  - 2.6
  - 2.7
before_install:
 - sudo apt-get update
 - sudo apt-get install gcc gfortran python-dev libatlas-base-dev liblapack-dev liblapack3gf
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install . --use-mirrors
script:
  - nosetests --with-coverage --cover-package=neurotools
