language: python
python:
  - 2.5
  - 2.6
  - 2.7

install:
  - pip install -r requirements.txt --use-mirrors
  - python setup.py install
script:
  - nosetests --with-coverage --cover-package=neurotools
